### ISSUE TITLE
Menu does not work

### ISSUE THREAD

**Issue by DCphat6** [nurlan-aliyev/RestaurantManagementSystem#1]
Download code to rpi, select menu items , nothing works but the about button. I can open db with db viewer but that's it.

**Comment by nurlan-aliyev** [comment]
I couldn't understand the issue you are facing, please read the updated [README.md](https://github.com/nurlan-aliyev/RestaurantManagementSystem/blob/main/README.md) and try again. If it doesn't work, please fork the project, make changes and the make a PR so I can look into.
